### ISSUE TITLE
Code::Block and Autotool build project are broken

### ISSUE THREAD

**Issue by avilleret** [CICM/CreamLibrary#13]
I realize a while ago that building Cream with autotool or Code::blocks leads to undefined symbol.
Some setup functions have been added to `c.library.cpp` but the Makefile.am and c.library.cbp files doesn't include the source that implements those setup function.

I know this is a big deal to maintain a working crossplatform build system in a working state.
And since you seems to use Xcode on OS X, you should have a look to CMake.
This is a meta build system which can produce IDE project (Apple XCode, Microsoft Visual Studio, QtCreator...) and valid tool chain. 
Thus only the CMake system should be updated each time you add a source.
Then cmake produces the build project for each platform.

This is what we are using with Jamoma (both for Core and Implementation (Max & Pd) build).

**Comment by avilleret** [comment]
BTW, the CICMwrapper already have a CMakelists.txt : https://github.com/avilleret/CicmWrapper/tree/feature/CMakeLists.txt

**Comment by pierreguillot** [comment]
Autotools seems to work for us, we can compile with it on Linux and MacOs . What are the undefined symbols ? Is it still broken ? Anyway, I going to have a look on CMake. Thanks.

**Comment by avilleret** [comment]
ho sorry, my mistake, the build system is not broken but produce a non working binary.
And I'm referring to the actual state of the dev branch.
The master branch build and load fine but there are some others issues, I'll open a pull request to fix those.
