### ISSUE TITLE
gop inside gop render error

### ISSUE THREAD

**Issue by husk00** [CICM/CreamLibrary#17]
Trying to create a c.bang object (or every other c gui object) inside a GOP as abstraction and then instanciate it inside another GOP the c graphic object positioning is wrong. It renders on the main cavas respect to the abstraction GOP where the object is and not respect to the main GOP where the abstraction actually is positioned,
You can download an exemple of this behaviour from: http://estereotips.net/release/c.gop.bug.tar.gz 

My system is a Gnu/Linux Ubuntu 64bit, intel hd.

thanks

**Comment by pierreguillot** [comment]
I thought that this problem was solved... Can you give me the versions of the library and of Pure Data ?
Cheers

**Comment by husk00** [comment]
pd vanilla 0.46-7
Cream version 0.2
 FYI same issue also with Pd-l2ork version 20150730

**Comment by pierreguillot** [comment]
The 0.4 should fix the problem.

**Comment by husk00** [comment]
I confirm that it is fixed with version 0.4 under vanilla.
I couldn't try it on extended.
Sadly the binary doesn't work with pd-l2ork.
Trying to compile Cream myself I encountresd an error, still trying to understand what is it.
BTW, thanks for the update.
