### ISSUE TITLE
Compilation issue on Linux (64 bit Arch Linux)

### ISSUE THREAD

**Issue by marierm** [CICM/CreamLibrary#6]
Hi,
I am trying to compile the CreamLibrary on Linux (64 bit) for PD Vanilla.  First, I cloned the repo and ran 'git submodule init' and 'git submodule update'.  I then ran into a first issue when executing autogen.sh.
Makefile.am:30: error: required directory ./Package/Cream does not exist
It seems that the folder Package/cream (lowercase 'c') should be renamed to Package/Cream.  Or that the makefile.am and configure.ac files should be modified accordingly.

**Comment by pierreguillot** [comment]
Problem solved, I'm using "Cream" folder now. Thank again !
