### ISSUE TITLE
where is  vDSP_polar defined ?

### ISSUE THREAD

**Issue by avilleret** [CICM/CreamLibrary#8]
I notice the use of  `vDSP_polar` in  https://github.com/CICM/CreamLibrary/blob/master/Chocolate/c.spectroscope_tilde.cpp#L239

Where is this function defined ?
At least, building fails on Ubuntu because of that.

Is it from DSPTool [1] library ?
This library seems to be made for Mac OS only.
So using it reduce the compatibility of Cream library to that OS, which is I think a great pity.
For only on function, I do think it is possible to rewrite it in a cross-platform way.

[1] : https://github.com/eddyc/DSPTools

**Comment by pierreguillot** [comment]
Hi,
My mistake, I've create a dev branch !
